version: '3.3'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9000:9090
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
  PVsim:
    build: .
    image: pvsim:0.0.1
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - ./data:/code/src/main/resources:rw
      - ./configs/ucy.conf:/code/configs/solarpark.conf:rw
    ports:
      - 4567:4567 
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always
  fronius:
    build: ./fronius-to-prometheus
    image: python-fronius:0.0.1
    environment:
      FRONIUS_URL: "PVsim:4567"
      FRONIUS_SENSORS_PATH: "solar_api/v1/GetSensorRealtimeData.cgi?DataCollection=NowSensorData&Scope=System"
      FRONIUS_PV_PATH: "solar_api/v1/GetPowerFlowRealtimeData.fcgi"
      PREFIX: "cyprus__nicosia__ucy__dc1__fronius_"
      FRONIUS_TIMEOUT: 15
    ports:
      - 19999:19999
  consul-server:
    image: hashicorp/consul:1.9.3
    container_name: consul-server
    restart: always
    volumes:
     - ./consul/server.json:/consul/config/server.json:ro
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"
volumes:
  prometheus-data: {}
  grafana_data: {}
