global:
  scrape_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name:       'services'
    static_configs:
      - targets: ['localhost:9090']
#  - job_name:       'fronius'
#    metrics_path: '/api/v1/allmetrics'
#    static_configs:
#      - targets: ['fronius:19999']
  - job_name: consul-server
    scrape_interval: 15s
    honor_labels: true
    consul_sd_configs:
    - server: localhost:8500
      services:
       - consul-server
