global:
  scrape_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
#  - job_name:       'services'
#    static_configs:
#      - targets: ['localhost:9090']
  - job_name: consul-server
    consul_sd_configs:
      - server: consul-server:8500
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*,fronius,.*
        action: keep
    metrics_path: '/api/v1/allmetrics'
    params:
      format: [prometheus]
    honor_labels: true
    scrape_interval: 15s